### ISSUE TITLE
[DEPRECATION] overriding init without calling this._super

### ISSUE THREAD

**Issue by blimmer** [ember-cli-deploy/ember-cli-deploy-display-revisions#11]
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (/Users/blimmer/code/webapps/my-app/node_modules/ember-cli-deploy-display-revisions/lib/scm-table.js:8:29)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (/Users/blimmer/code/webapps/my-app/node_modules/ember-cli-deploy-display-revisions/lib/legacy-table.js:6:29)
```

**Comment by blimmer** [comment]
actually looks like there are a few things we need to call per

https://github.com/ember-cli/core-object/commit/8458b87366b10af8001291a95613257a72fd0629
