### ISSUE TITLE
Deprecation Warning for usage of this._super.init

### ISSUE THREAD

**Issue by kattybilly** [ember-cli-deploy/ember-cli-deploy-display-revisions#13]
DEPRECATION: 
```
Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (......./node_modules/ember-cli-deploy-display-revisions/lib/scm-table.js:8:29)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (......./node_modules/ember-cli-deploy-display-revisions/lib/legacy-table.js:6:29)
```

**Comment by typeoneerror** [comment]
@kattybilly ran into this too. you should update to latest as this was fixed by https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/pull/12

**Comment by kattybilly** [comment]
Thanks for the PR mention @typeoneerror , I missed upon checking across the updated version.
